# Generated by Django 5.0.6 on 2024-05-30 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Staff', '0004_workers_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workers',
            name='phone_number',
            field=models.CharField(blank=True, max_length=17, null=True),
        ),
    ]
